language: php
php:
  - 5.6

before_script:
  # install hook server
  - git clone --depth=1 https://github.com/doubleleft/hook.git
  - cd ./hook && sh ./.travis/install_dependencies.sh && cd -
  - travis_retry composer self-update
  - travis_retry composer install --no-dev --prefer-dist -d hook

  # install javascript dependencies and compile dist files
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - npm install
  - grunt

script:
  - grunt qunit
