language: php
php:
  - 5.6

addons:
  sauce_connect: true

before_script:
  # install hook server
  - git clone --depth=1 https://github.com/doubleleft/hook.git
  - travis_retry composer self-update
  - travis_retry composer install --no-dev --prefer-dist -d hook
  - cd ./hook && sh ./.travis/install_server.sh && cd -

  # create default app for testing
  - curl -XPOST http://hook.dev/index.php/apps --data '{"app":{"name":"hook-javascript"}}' > tests/app.json
  - cat tests/app.json

  # install javascript dependencies and compile dist files
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - npm install
  - grunt

script:
  - grunt travis
