language: php
php:
  - 5.6

before_script:
  - git clone https://github.com/doubleleft/hook.git
  - sudo sh ./hook/.travis/install_dependencies.sh
  - travis_retry composer self-update
  - travis_retry composer install -d hook
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - npm install
  - grunt

script:
  - grunt qunit
